# Generated by Django 2.2.12 on 2020-05-18 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roles',
            options={'verbose_name_plural': 'perfiles'},
        ),
    ]
