# Generated by Django 2.2.12 on 2020-05-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datosuser',
            options={'verbose_name': 'Datos del usuario', 'verbose_name_plural': 'Informacion'},
        ),
        migrations.AlterModelOptions(
            name='detaroles',
            options={'verbose_name': 'Roles de usuario', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='habilidades',
            options={'verbose_name': 'Habilidades de usuario', 'verbose_name_plural': 'Competencias'},
        ),
        migrations.AlterModelOptions(
            name='rates',
            options={'verbose_name': 'Porcentaje de nivel de habilidad', 'verbose_name_plural': 'Niveles de usuario'},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'verbose_name': 'Roles de usuario', 'verbose_name_plural': 'perfiles'},
        ),
        migrations.AlterField(
            model_name='habilidades',
            name='DescHabil',
            field=models.TextField(verbose_name='Descripcion de la habilidad'),
        ),
    ]
