# Generated by Django 2.2.12 on 2020-05-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0002_auto_20200507_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosuser',
            name='ApeUser',
            field=models.CharField(max_length=255, null=True, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='datosuser',
            name='GeneUser',
            field=models.CharField(choices=[('Masculino', 'M'), ('Femenino', 'F'), ('Otro', 'Otro')], default='Otro', max_length=20, null=True, verbose_name='Genero'),
        ),
        migrations.AddField(
            model_name='datosuser',
            name='NombUser',
            field=models.CharField(max_length=255, null=True, verbose_name='Nombres'),
        ),
        migrations.AddField(
            model_name='datosuser',
            name='ProfeUser',
            field=models.CharField(max_length=70, null=True, verbose_name='Profesion'),
        ),
        migrations.AlterField(
            model_name='datosuser',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='datosuser',
            name='modificado',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Modificado el'),
        ),
        migrations.AlterField(
            model_name='datosuser',
            name='teleUser',
            field=models.CharField(max_length=20, verbose_name='Numero de Telefono'),
        ),
        migrations.AlterField(
            model_name='datosuser',
            name='userDNI',
            field=models.CharField(max_length=20, verbose_name='Identificacion'),
        ),
        migrations.AlterField(
            model_name='detaroles',
            name='addUser',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='habilidades',
            name='NombHabil',
            field=models.CharField(max_length=155, verbose_name='Competencia'),
        ),
    ]
