# Generated by Django 2.2.12 on 2020-05-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0002_auto_20200518_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habiluser',
            name='DescHabil',
            field=models.TextField(max_length=2000, verbose_name='Descripcion de la habilidad'),
        ),
    ]
