# Generated by Django 2.2.12 on 2020-05-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0003_auto_20200513_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilidades',
            name='prof',
            field=models.CharField(max_length=200, null=True, verbose_name='Profesion'),
        ),
    ]
