# Generated by Django 2.2.12 on 2020-05-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0005_auto_20200519_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habiluser',
            name='NombHabil',
            field=models.CharField(max_length=100, verbose_name='Habilidad'),
        ),
    ]
