# Generated by Django 2.2.12 on 2020-05-22 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0006_auto_20200521_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosuser',
            name='fotoUser',
            field=models.ImageField(default='user.png', upload_to='img/perfiles', verbose_name='Foto de perfil'),
        ),
    ]
