# Generated by Django 2.2.12 on 2020-05-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomTiDo', models.CharField(max_length=50, verbose_name='Tipo de documento')),
            ],
        ),
    ]
